
name: Update badges

on:
  schedule:
    # Runs at 0am UTC every day
    - cron: "0 0 * * 0"
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-22.04
    steps:
      - name: Badges - Readme
        uses: berviantoleo/accredible-actions@main
        with:
          username: 'berviantoleo'
          token: ${{ secrets.GITHUB_TOKEN }}
